feat(dto): export `ThirdpartyRequestsVerifications*` types
mojaloop/api-snippets pull request #101
Opened 2021-08-05 06:03 UTC by lewisdaly

Is this the right way to do it? I noticed that these weren't added to the `index.ts` automatically.

2021-08-05 10:30 UTC, kleyow commented
@lewisdaly Yep. Add a test though just to make sure it's being exported and generated in https://github.com/mojaloop/api-snippets/blob/master/tests/dto/thirdparty.test.ts

2021-08-05 10:31 UTC, kleyow requested changes
@lewisdaly Yep. Add a test though just to make sure it's being exported and generated in https://github.com/mojaloop/api-snippets/blob/master/tests/dto/thirdparty.test.ts

2021-08-05 13:32 UTC, kleyow commented on tests/dto/thirdparty.test.ts
> +          authentication: 'U2F',
I think this request body needs to be updated to handle `clientDataJson`/`authenticatorData`/`signature`/`userHandle` https://webauthn.guide/#authentication

2021-08-05 13:33 UTC, kleyow approved these changes

2021-08-05 17:50 UTC, kleyow requested changes
https://github.com/mojaloop/api-snippets/pull/99/files 
Totally forgot that I started addressing those changes here.

2021-08-05 18:09 UTC, kleyow commented
Once we settle on the schema changes I have the updates to the `central-ledger` and `sdk-standard-components` standing by.

2021-08-06 00:52 UTC, lewisdaly commented
> https://github.com/mojaloop/api-snippets/pull/99/files
> Totally forgot that I started addressing those changes here.

Yeah I was wondering about that... do you want to merge that PR in first, then we can do mine?

2021-08-06 01:12 UTC, kleyow commented
Sounds good. It's building now.

2021-08-09 01:57 UTC, kleyow approved these changes

2021-08-09 02:04 UTC, kleyow commented on tests/dto/thirdparty.test.ts
> +          authentication: 'U2F',
Not sure how we want to change this payload to include `FIDOPublicKeyCredentialAssertion` but lets do that in another PR.

2021-08-09 02:09 UTC, merged