refactor: change consents id put responses to be more explicit
mojaloop/api-snippets pull request #35
Opened 2020-10-06 14:43 UTC by kleyow

Continuing with the trend of null fields being removed.

PUT /consents/{{ID}} now represented by three responses.

> Auth-Service updating the PISP with a challenge to sign
Represented by ConsentsIDPutResponseUnsigned.yaml

> PISP updating the Auth-Service with the signed challenge
Represented by ConsentsIDPutResponseSigned.yaml

> Auth-Service updating the PISP and DFSP with the finalized credential
Represented by ConsentsIDPutResponseVerified.yaml

2020-10-07 06:34 UTC, eoln requested changes
- little inconsistency
- a lot of renaming - let see what @lewisdaly would say

2020-10-07 06:34 UTC, eoln commented on docs/thirdparty-openapi3-snippets.yaml
> +    ConsentsIDPutResponseSigned:
Signed or Unsigned ?

2020-10-07 06:44 UTC, kleyow commented on docs/thirdparty-openapi3-snippets.yaml
> +    ConsentsIDPutResponseSigned:
fixed. thanks.

2020-10-07 11:18 UTC, eoln approved these changes
I would wait on @lewisdaly to see his opinion about renaming

2020-10-07 15:35 UTC, lewisdaly requested changes
Just a couple minor points. I commented on the compiled file, but hopefully it's not too hard to make the changes on the individual files.

Thanks for this Kevin, I admire your pursuit for good type definitions.

2020-10-07 15:35 UTC, lewisdaly commented on docs/thirdparty-openapi3-snippets.yaml
> +        The HTTP request `PUT /consents/{ID}` is used to request a PISP to sign a challenge.
I think this should be 
```
The HTTP request `PUT /consents/{ID}` is user by the PISP to update a Consent with a signed challenge and register a credential.
```

2020-10-07 15:35 UTC, lewisdaly commented on docs/thirdparty-openapi3-snippets.yaml
> +        The HTTP request `PUT /consents/{ID}` is used to request a PISP to sign a challenge.
```suggestion
        The HTTP request `PUT /consents/{ID}` is used by the DFSP or Auth-Service to update a Consent object once it has been Verified.
```

2020-10-07 15:35 UTC, lewisdaly commented on docs/thirdparty-openapi3-snippets.yaml
> +        - type
`id` should be required

2020-10-07 16:41 UTC, kleyow commented
@lewisdaly addressed comments. thank you.

2020-10-08 02:40 UTC, lewisdaly approved these changes

2020-10-08 04:57 UTC, merged